# Generated by Django 2.0.1 on 2018-03-31 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepics/', verbose_name='Profile Picture')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Physical Address')),
                ('cell', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('company_name', models.CharField(blank=True, max_length=15, null=True)),
                ('company_adress', models.CharField(blank=True, max_length=15, null=True)),
                ('company_cell', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepics/', verbose_name='Profile Picture')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Physical Address')),
                ('cell', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('levels', models.ManyToManyField(to='questions.Level')),
                ('subjects', models.ManyToManyField(to='questions.Subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
